#!/usr/bin/env python2

import sys
from libwebsocket import WebsocketClient

def onmessage(ws, data):
    print data

def onerror(ws, conn):
    print "error occurred. closing conection"
    ws.readyState = 3
    conn.close()
    sys.exit(1)

if __name__=='__main__':
    print 'opening connection'
    ws = WebsocketClient('ws://127.0.0.1:1234/test', 'test', None, onmessage,
                         onerror, None)
    while ws.readyState == 1:
        msg = sys.stdin.readline()
        ws.send(msg)
