#!/usr/bin/env python2

import socket
from libwebsocket import WebsocketServer

def onopen(ws):
    print "connection established"

def onmessage(ws, data):
    print "message received:"
    print data
    ws.send('server response')

def onerror(conn):
    print "error occurred. closing conection"
    ws.readyState = 3
    conn.close()
    sys.exit(1)

def onclose():
    print "connection closed"

if __name__=='__main__':
    port = 1234
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('', port))
    print "Listening"
    s.listen(1)
    conn, cli_addr = s.accept()
    print "connection received. will call websocket"
    ws = WebsocketServer(conn, port, onopen, onmessage, onerror, onclose)
